version: '3'

volumes: 
  gem_cache_dev:
  data_dev:
  shared_data:

services:
  db:
    image: postgres:13.1-alpine
    container_name: notebook
    restart: always
    volumes:
      - data_dev:/var/lib/postgresql/data
      - shared_data:/var/shared
    env_file: .env
    ports: 
      - "5437:5432"
